use crate::presets::{Crop, Dither, Format, Preset};

pub fn default_presets() -> Vec<Preset> {
    vec![
        // GIF presets — mirror existing SendTo_FFmpeg scripts
        Preset {
            id: "gif_420_lq_20".into(),
            name: "GIF 420px LQ 20fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_420px_LQ_20fps".into(),
            width: Some(420),
            height: None,
            fps: Some(20),
            crop: None,
            palette_colors: Some(96),
            dither: Some(Dither::Bayer),
            bayer_scale: Some(3),
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            icon: None,
            order: 0,
        },
        Preset {
            id: "gif_500_mq_25".into(),
            name: "GIF 500px MQ 25fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_500px_MQ_25fps".into(),
            width: Some(500),
            height: None,
            fps: Some(25),
            crop: None,
            palette_colors: Some(128),
            dither: Some(Dither::Bayer),
            bayer_scale: Some(3),
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            icon: None,
            order: 1,
        },
        Preset {
            id: "gif_800_hq_24".into(),
            name: "GIF 800px HQ 24fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_800px_HQ_24fps".into(),
            width: Some(800),
            height: None,
            fps: Some(24),
            crop: None,
            palette_colors: Some(192),
            dither: Some(Dither::Sierra24a),
            bayer_scale: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            icon: None,
            order: 2,
        },
        Preset {
            id: "gif_800_hq_30".into(),
            name: "GIF 800px HQ 30fps".into(),
            enabled: true,
            format: Format::Gif,
            suffix: "_800px_HQ_30fps".into(),
            width: Some(800),
            height: None,
            fps: Some(30),
            crop: None,
            palette_colors: Some(192),
            dither: Some(Dither::Sierra24a),
            bayer_scale: None,
            crf: None,
            preset_speed: None,
            video_bitrate: None,
            audio_bitrate: None,
            use_cuda: None,
            target_max_mb: None,
            icon: None,
            order: 3,
        },
        // MP4 presets — sizing
        Preset {
            id: "mp4_720p".into(),
            name: "MP4 720p".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_720p".into(),
            width: Some(1280),
            height: Some(720),
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: Some(23),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 4,
        },
        Preset {
            id: "mp4_1080p".into(),
            name: "MP4 1080p".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_1080p".into(),
            width: Some(1920),
            height: Some(1080),
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("160k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 5,
        },
        Preset {
            id: "mp4_compressed".into(),
            name: "MP4 Compressed".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_compressed".into(),
            width: Some(1280),
            height: None,
            fps: None,
            crop: None,
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: None,
            preset_speed: Some("medium".into()),
            video_bitrate: Some("2M".into()),
            audio_bitrate: Some("96k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 6,
        },
        // MP4 presets — cropping
        Preset {
            id: "mp4_crop_16x9".into(),
            name: "MP4 → 16:9 (crop)".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_16x9".into(),
            width: None,
            height: None,
            fps: None,
            crop: Some(Crop::H16x9),
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 7,
        },
        Preset {
            id: "mp4_crop_9x16".into(),
            name: "MP4 → 9:16 (crop)".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_9x16".into(),
            width: None,
            height: None,
            fps: None,
            crop: Some(Crop::V9x16),
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 8,
        },
        Preset {
            id: "mp4_crop_1x1".into(),
            name: "MP4 → 1:1 (crop)".into(),
            enabled: true,
            format: Format::Mp4,
            suffix: "_1x1".into(),
            width: None,
            height: None,
            fps: None,
            crop: Some(Crop::S1x1),
            palette_colors: None,
            dither: None,
            bayer_scale: None,
            crf: Some(22),
            preset_speed: Some("medium".into()),
            video_bitrate: None,
            audio_bitrate: Some("128k".into()),
            use_cuda: Some(false),
            target_max_mb: None,
            icon: None,
            order: 9,
        },
    ]
}

pub fn default_custom() -> Preset {
    Preset {
        id: "custom".into(),
        name: "Custom".into(),
        enabled: false,
        format: Format::Gif,
        suffix: "_custom".into(),
        width: Some(500),
        height: None,
        fps: Some(24),
        crop: None,
        palette_colors: Some(128),
        dither: Some(Dither::Bayer),
        bayer_scale: Some(3),
        crf: Some(23),
        preset_speed: Some("medium".into()),
        video_bitrate: None,
        audio_bitrate: Some("128k".into()),
        use_cuda: Some(false),
        target_max_mb: None,
        icon: None,
        order: 0,
    }
}
